python3 << 'EOF'
lines = [
    "# Makefile for Epsilon_CPU\n",
    "CC = gcc\n",
    "CXX = g++\n",
    "CFLAGS = -std=c11 -Wall -Wextra -Werror -g\n",
    "CXXFLAGS = -std=c++17 -Wall -Wextra -Werror -g\n",
    "INCLUDES = -I./lib -I./src\n",
    "SRCDIR = src\n",
    "OBJDIR = obj\n",
    "TARGET = epsilon_cpu\n",
    "\n",
    "C_SRCS = $(wildcard $(SRCDIR)/*.c) \\\n",
    "         $(wildcard lib/*.c) \\\n",
    "         $(wildcard lib/alu/*.c) \\\n",
    "         $(wildcard lib/err/*.c) \\\n",
    "         $(wildcard lib/scheduler/*.c) \\\n",
    "         $(wildcard lib/command/*.c) \\\n",
    "         $(wildcard lib/interrupts/*.c) \\\n",
    "         $(wildcard lib/logic_gates/*.c)\n",
    "\n",
    "CPP_SRCS = $(wildcard lib/sys_status/*.cpp)\n",
    "\n",
    "C_OBJS = $(patsubst %.c,$(OBJDIR)/%.o,$(C_SRCS))\n",
    "CPP_OBJS = $(patsubst %.cpp,$(OBJDIR)/%.o,$(CPP_SRCS))\n",
    "OBJS = $(C_OBJS) $(CPP_OBJS)\n",
    "\n",
    "TOTAL := $(words $(OBJS))\n",
    "COUNT_FILE := $(OBJDIR)/.count\n",
    "\n",
    "GREEN = \\033[1;32m\n",
    "BLUE  = \\033[1;34m\n",
    "RESET = \\033[0m\n",
    "\n",
    ".DEFAULT_GOAL := run\n",
    ".PHONY: all run clean\n",
    "\n",
    "all: $(TARGET)\n",
    "\n",
    "run: $(TARGET)\n",
    "\t./$(TARGET)\n",
    "\n",
    "$(TARGET): $(OBJS)\n",
    "\t$(CXX) $(OBJS) -o $@\n",
    "\t@echo \"$(GREEN)[BUILD OK]$(RESET) $(TARGET)\"\n",
    "\n",
    "$(OBJDIR)/%.o: %.c\n",
    "\t@mkdir -p $(dir $@)\n",
    "\t$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@\n",
    "\t@count=$$(cat $(COUNT_FILE) 2>/dev/null || echo 0); \\\n",
    "\tcount=$$((count + 1)); \\\n",
    "\techo $$count > $(COUNT_FILE); \\\n",
    "\tprintf \"$(GREEN)[%d$(RESET)/$(BLUE)%d$(RESET)] $(GREEN)OK!$(RESET) %s\\n\" \\\n",
    "\t$$count $(TOTAL) $@\n",
    "\n",
    "$(OBJDIR)/%.o: %.cpp\n",
    "\t@mkdir -p $(dir $@)\n",
    "\t$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@\n",
    "\t@count=$$(cat $(COUNT_FILE) 2>/dev/null || echo 0); \\\n",
    "\tcount=$$((count + 1)); \\\n",
    "\techo $$count > $(COUNT_FILE); \\\n",
    "\tprintf \"$(GREEN)[%d$(RESET)/$(BLUE)%d$(RESET)] $(GREEN)OK!$(RESET) %s\\n\" \\\n",
    "\t$$count $(TOTAL) $@\n",
    "\n",
    "clean:\n",
    "\trm -rf $(OBJDIR) $(TARGET) $(COUNT_FILE)\n",
    "\t@echo \"$(GREEN)[CLEAN OK]$(RESET)\"\n",
]

with open('Makefile', 'w') as f:
    f.writelines(lines)

print("Tamam! Doğrulama:")
with open('Makefile', 'r') as f:
    for i, line in enumerate(f, 1):
        if line.startswith('\t'):
            print(f"  Satir {i}: TAB OK -> {repr(line[:30])}")
EOF
